### ISSUE TITLE
Rison Error when changing color in Kibana

### ISSUE THREAD

**Issue by maurermj08** [maurermj08/efetch#8]
When changing the color of a visualization in Kibana, the field is updated with "colors:(file:#FF0000)" which breaks the rison library. Retrieve invalid character '#' error.

``````
ERROR:root:Failed to parse rison: (filters:!(),options:(darkTheme:!f),panels:!((col:10,id:xpquick-action,panelIndex:1,row:1,size_x:3,size_y:4,type:visualization),(col:7,id:xpquick-ext,panelIndex:2,row:1,size_x:3,size_y:4,type:visualization),(col:1,id:xpquick-histogram,panelIndex:3,row:1,size_x:6,size_y:4,type:visualization),(col:1,columns:!(pathspec,path,type),id:xpquick,panelIndex:5,row:5,size_x:9,size_y:4,sort:!(datetime_atime,desc),type:search),(col:10,id:xpquick-type,panelIndex:6,row:5,size_x:3,size_y:2,type:visualization),(col:10,id:xpquick-count,panelIndex:7,row:7,size_x:3,size_y:2,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:'xpquick one',uiState:(P-2:(vis:(legendOpen:!t)),P-6:(vis:(colors:(file:#2F575E)))))
Traceback (most recent call last):
  File "/home/user/GIT/efetch/efetch_server/utils/db_util.py", line 110, in get_theme
    a_parsed = rison.loads(a_parameter)
  File "build/bdist.linux-x86_64/egg/rison/decoder.py", line 225, in loads
    return Parser().parse(s, format=format)
  File "build/bdist.linux-x86_64/egg/rison/decoder.py", line 34, in parse
    value = self.read_value()
  File "build/bdist.linux-x86_64/egg/rison/decoder.py", line 45, in read_value
    return self.parse_open_paren()
  File "build/bdist.linux-x86_64/egg/rison/decoder.py", line 120, in parse_open_paren
    v = self.read_value()
  File "build/bdist.linux-x86_64/egg/rison/decoder.py", line 45, in read_value
    return self.parse_open_paren()
  File "build/bdist.linux-x86_64/egg/rison/decoder.py", line 120, in parse_open_paren
    v = self.read_value()
  File "build/bdist.linux-x86_64/egg/rison/decoder.py", line 45, in read_value
    return self.parse_open_paren()
  File "build/bdist.linux-x86_64/egg/rison/decoder.py", line 120, in parse_open_paren
    v = self.read_value()
  File "build/bdist.linux-x86_64/egg/rison/decoder.py", line 45, in read_value
    return self.parse_open_paren()
  File "build/bdist.linux-x86_64/egg/rison/decoder.py", line 120, in parse_open_paren
    v = self.read_value()
  File "build/bdist.linux-x86_64/egg/rison/decoder.py", line 45, in read_value
    return self.parse_open_paren()
  File "build/bdist.linux-x86_64/egg/rison/decoder.py", line 120, in parse_open_paren
    v = self.read_value()
  File "build/bdist.linux-x86_64/egg/rison/decoder.py", line 62, in read_value
    raise ParserException("invalid character: '" + c + "'")
ParserException: invalid character: '#'```

``````

**Comment by maurermj08** [comment]
I know this is a bug in the RISON project, but I think it would be better to leave this here, so it actually gets fixed
